Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Style/RedundantSelf:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
